name: filesearch
version: '1.0'
summary: Command-line file search application in C
description: |
  This is a command-line file search application written in C. The application searches for a specified filename or subdirectory in a directory and all its subdirectories and provides a list of matching files or subdirectories. https://github.com/EndrDragon44/FileSearch

grade: stable
confinement: strict

apps:
  file-search:
    command: bin/filesearch

parts:
  file-search:
    plugin: make
    source: .
    build-packages:
      - gcc
    organize:
      filesearch: bin/
    stage-packages:
      - libc6
